# Generated by Django 3.0.3 on 2020-07-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterCredit',
        ),
        migrations.AddField(
            model_name='setting',
            name='left_credit',
            field=models.CharField(default='New', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='right_credit',
            field=models.CharField(default='New 2', max_length=120),
            preserve_default=False,
        ),
    ]
