# Generated by Django 3.0.8 on 2020-07-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20200716_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='footer_1',
        ),
        migrations.AddField(
            model_name='setting',
            name='first_info',
            field=models.CharField(default='p', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='second_info',
            field=models.CharField(default='p', max_length=120),
            preserve_default=False,
        ),
    ]
