# Generated by Django 3.0.8 on 2020-07-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20200722_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='right_credit',
            field=models.URLField(max_length=120),
        ),
    ]
